spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=ture&characterEncoding=utf-8
    username: root
    password: wangrui
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.wruins: info
  file:
    path: log/blog-pro.log

server:
  port: 8081